create table if not exists absences (id bigint generated by default as identity primary key, created_at timestamptz default now(), date_absence date not null, type_evenement text not null default 'Entraînement', joueur integer not null, justifiee boolean not null default false, motif text not null default '');
alter table absences enable row level security;
create policy "Lecture absences" on absences for select to anon using (true);
create policy "Ajout absences" on absences for insert to anon with check (true);
create policy "Suppression absences" on absences for delete to anon using (true);
create policy "Modification absences" on absences for update to anon using (true) with check (true);